# Generated by Django 5.0.6 on 2024-06-27 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=255)),
                ('forma_farmaceutica', models.CharField(max_length=255)),
                ('concentracion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombre1', models.CharField(max_length=50)),
                ('nombre2', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido1', models.CharField(max_length=50)),
                ('apellido2', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(max_length=10)),
                ('celular', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('ocupacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEnfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSangre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sangre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombre1', models.CharField(max_length=50)),
                ('nombre2', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido1', models.CharField(max_length=50)),
                ('apellido2', models.CharField(blank=True, max_length=50, null=True)),
                ('celular', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.especialidad')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Habitos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('frecuencia', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='AntecedentesPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='AntecedentesFamiliares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('relacion', models.CharField(max_length=50)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='AntecedenteClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Alergias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='PrescripcionMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis', models.CharField(max_length=50)),
                ('frecuencia', models.CharField(blank=True, max_length=50, null=True)),
                ('duracion', models.CharField(blank=True, max_length=50, null=True)),
                ('instrucciones', models.CharField(blank=True, max_length=255, null=True)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='EnvioPrescripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_envio', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_envio', models.CharField(blank=True, max_length=1, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('prescripcion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consultorio.prescripcionmedica')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro_medico', models.DateTimeField()),
                ('razon', models.CharField(max_length=255)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='prescripcionmedica',
            name='registro_medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.registromedico'),
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_diagnostico', models.DateTimeField()),
                ('enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.enfermedad')),
                ('registro_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.registromedico')),
            ],
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presion', models.CharField(blank=True, max_length=7, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('talla', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('imc', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('registro_medico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consultorio.registromedico')),
            ],
        ),
        migrations.AddField(
            model_name='enfermedad',
            name='tipo_enfermedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.tipoenfermedad'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_sangre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.tiposangre'),
        ),
        migrations.CreateModel(
            name='Traumas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.paciente')),
            ],
        ),
    ]
